In [ ]:
import numpy as np
import pandas as pd
# from nltk import bigrams,trigrams
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
import re
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from textblob import TextBlob
from sklearn.decomposition import TruncatedSVD
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
from nltk.stem import PorterStemmer
from collections import defaultdict
from sklearn.feature_extraction.text import TfidfVectorizer
nltk.download('wordnet') # first-time use only
import nltk, string, numpy
nltk.download('punkt') # first-time use only
import sys
np.set_printoptions(threshold=sys.maxsize)
from sklearn import preprocessing
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.decomposition import TruncatedSVD
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
#Read review Content File

In [ ]:
file1 = open("/content/reviewContent")
review = defaultdict(list)
for row in file1:
    # temp = row.split()
    text = re.split(r'\t+', row)
    row = re.sub('[^a-zA-Z0-9 \n\..]', '', text[-1])
    review[text[1]].append(row)

file1.close()

In [ ]:
#Read Feature CSV

In [ ]:
file1 = open("/content/featuresAll.csv")
arr = []
for row in file1:
    text = re.split(r'\t+', row)
    arr.append(text)

file1.close()

In [ ]:
#print(arr[1])

['0.195833333,0.395833333,143,0.896513588,141,0.043510066,0.005451478,4.00952381,210,37.41025641,39,0,0.974358974,0.025641026,1.625,3,136.0394737\n']


In [ ]:
#a1 = preprocessing.normalize(np.array(arr[1:]), norm='max', axis=1)

In [ ]:
#print(review['1'])

['My wife and I took my parents there for lunch and were greeted by stares from the staff with no greeting whatsoever despite there being only five people in the entire place. This was followed by a rude abrupt waitress who acted like we had to speed talk to place an order. To cap off this wonderful experience the pizza was non descript and the pasta tasted like it had been ordered from a diner. So poor in fact that my two kids who normally love pasta refused to eat theirs. Wont be back and will definitely not recommend this place to anyone.\n', 'Got a margarita pizza. First off let me say very expensive that one pie came out to 25 with 2 simple toppings on it. Secondly the was a piece of hair in it. Also the sauce was bland. My table was all oily. Definitely not recommending this place might as well go down the block to Tommys. Again HORRIBLE.\n', 'The food is average pizzeria and not cheap. Add that to the fact that I puked my guts out in the bathroom during the meal and Ive decided 

In [ ]:
#print(data1[0])

the food snack select popular greek dishes. the appet tray good greek salad. We underwhelm main courses. there 45 tabl sometim hard get seated.


In [ ]:
#Tokenize the reviews to get content similarty matrix

In [ ]:

stemmer = nltk.stem.porter.PorterStemmer()
def StemTokens(tokens):
    return [stemmer.stem(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
def StemNormalize(text):
    return StemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))
lemmer = nltk.stem.WordNetLemmatizer()
def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))
TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
def cos_similarity(textlist):
    tfidf = TfidfVec.fit_transform(textlist)
    return (tfidf * tfidf.T).toarray()
sim = defaultdict(list)
for val in review:
    sim[val].append(cos_similarity(review[val]))

sim_final = defaultdict(list)
for val in sim:
  # for i in range(len(sim[val][0])):
  sim_final[val].append(numpy.mean(sim[val][0], axis = 1))
  sim_final[val].append(numpy.var(sim[val][0], axis = 1))

normalized_sim = defaultdict(list)
for val in sim_final:
  normalized_sim[val].append(preprocessing.normalize(np.array(sim_final[val]), norm='max', axis=1))

b = []
for val in normalized_sim:
  for i in range(len(normalized_sim[val][0][0])):
    b.append([val, normalized_sim[val][0][0][i], normalized_sim[val][0][1][i]])

ar = np.array(b)
np.savetxt('norm_similarity.csv', ar, delimiter=',',fmt='%s',header="ProductID,MeanSimilarity,Variance")

/usr/local/lib/python3.7/dist-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


In [ ]:
#print(sim_final['3'])
#print(a[1])

[array([0.05754274, 0.0439468 , 0.06243739, 0.10254905, 0.06513711,
       0.06796427, 0.07770346, 0.08850489, 0.08674516, 0.07251857,
       0.08224877, 0.07572205, 0.09205948, 0.05812363, 0.06453566,
       0.09319698, 0.08079935, 0.06893712, 0.07030854, 0.09922079,
       0.05671803, 0.07461461, 0.06838011, 0.0884723 , 0.10145704,
       0.04871571, 0.08292835, 0.07333725, 0.0812713 , 0.05756541,
       0.07766678, 0.08840682, 0.06829501, 0.0669811 , 0.10141578,
       0.10891447, 0.06887301, 0.06914226, 0.08880783, 0.07808225,
       0.05866798, 0.07998729, 0.08232838, 0.06235779, 0.08650873,
       0.08412268, 0.05356171, 0.07273922, 0.09309549, 0.07415134,
       0.07675214, 0.08442394, 0.08361678, 0.0679149 , 0.05889105,
       0.06690112, 0.05568495, 0.07800545, 0.09750947]), array([0.01726425, 0.01613061, 0.01625141, 0.01563996, 0.01669422,
       0.01592588, 0.01583896, 0.01519921, 0.01562516, 0.01561853,
       0.01571313, 0.01611816, 0.01586422, 0.01608892, 0.01563019,
    

In [ ]:
#Read Review Graph file

In [ ]:
file2 = open("/content/reviewGraph")
dic = defaultdict(list)
for row in file2:
    tr = row.split()
    dic[tr[1]].append(float(tr[-1]))
file2.close()

In [ ]:
#Read Metadata file

In [ ]:
file2 = open("/content/metadata")
d1 = []
d2 = []
for row in file2:
    tr = row.split()
    if int(tr[3]) == -1:
      d1.append(row)
    else:
      d2.append(row)
file2.close()

In [ ]:
#Create Product related features

In [ ]:

ar = []
for val in dic:
  ar.append([val, sum(dic[val])/len(dic[val]), 1 if len(dic[val]) == 1 else 0 , len(dic[val])])

a = np.array(ar)
np.savetxt('product.csv', a, delimiter=',',fmt='%s',header="ProductID,MeanRating,Signleton,numberOfReviews")
print(a)

[['0' '4.0095238095238095' '0' '210']
 ['1' '4.32806324110672' '0' '253']
 ['3' '4.169491525423729' '0' '59']
 ...
 ['920' '4.094771241830065' '0' '306']
 ['921' '4.171875' '0' '192']
 ['349' '4.185185185185185' '0' '108']]


In [ ]:
# print(len(d1))
# print(len(d2))

36885
322167


In [ ]:
#Train models and feature importance

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/featuresAll.csv')
labels = pd.read_csv('/content/labels.csv')

In [ ]:
from numpy import mean
from numpy import std
from pandas import read_csv
from matplotlib import pyplot
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_validate
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier

# load the dataset
def load_dataset(full_path):
	# load the dataset as a numpy array
	dataframe = read_csv(full_path, header=None, na_values='?')
	# drop rows with missing
	dataframe = dataframe.dropna()
	# split into inputs and outputs
	last_ix = len(dataframe.columns) - 1
	X, y = dataframe.drop(last_ix, axis=1), dataframe[last_ix]
	# select categorical and numerical features
	cat_ix = X.select_dtypes(include=['object', 'bool']).columns
	num_ix = X.select_dtypes(include=['int64', 'float64']).columns
	# label encode the target variable to have the classes 0 and 1
	y = LabelEncoder().fit_transform(y)
	return X.values, y, cat_ix, num_ix

# evaluate a model
def evaluate_model(X, y, model):
  # define evaluation procedure
  cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
  #evaluate model
  #scores = cross_val_score(model, X, y, scoring=['f1-score'], cv=cv, n_jobs=-1)

  scores = cross_validate(model, X, y, scoring=['precision', 'recall', 'f1', 'accuracy'], cv=cv, n_jobs=-1 )
  return scores

# define models to test
def get_models():
	models, names = list(), list()
	# CART
	#models.append(DecisionTreeClassifier())
	#names.append('CART')
	# SVM
	models.append(SVC(gamma='scale'))
	names.append('SVM')
	# Bagging
	#models.append(BaggingClassifier(n_estimators=100))
	#names.append('BAG')
	# RF
	#models.append(RandomForestClassifier(n_estimators=100))
	#names.append('RF')
	# GBM
	#models.append(GradientBoostingClassifier(n_estimators=100))
	#names.append('GBM')
	return models, names

# define the location of the dataset
#full_path = 'adult-all.csv'
# load the dataset
#X, y, cat_ix, num_ix = load_dataset(full_path)
X = df
Y = labels
# define models
models, names = get_models()
results = list()
# evaluate each model
for i in range(len(models)):
  # define steps
  #steps = [('c',OneHotEncoder(handle_unknown='ignore'),cat_ix), ('n',MinMaxScaler(),num_ix)]
  # one hot encode categorical, normalize numerical
  #ct = ColumnTransformer(steps)
  # wrap the model i a pipeline
  pipeline = Pipeline(steps=[('m',models[i])])
  # evaluate the model and store results
  scores = evaluate_model(X, Y, pipeline)
  print("SCORES")
  print(scores)
  results.append(scores)
  # summarize performance
  #print('>%s %.3f (%.3f)' % (names[i], mean(scores), std(scores)))
# plot the results
pyplot.boxplot(results, labels=names, showmeans=True)
pyplot.show()

In [ ]:
X1 = df.to_numpy()
Y = labels.to_numpy()
print(Y.shape)

(359052, 1)


In [ ]:
model = RandomForestClassifier(n_estimators=100)

pca = PCA(n_components=7)
skf = StratifiedKFold(n_splits=10)
fold_no = 1
for train_index, test_index in skf.split(X1, Y):
    X1_train = X1[train_index,:]
    X1_test = X1[test_index,:]
    Y_train = Y[train_index,:]
    Y_test = Y[test_index,:]
    pca.fit(X1_train)
    X_train = pca.transform(X1_train)
    X_test = pca.transform(X1_test)  
    model.fit(X_train, np.ravel(Y_train,order='C'))
    predictions = model.predict(X_test)
    print('Fold',str(fold_no),'Accuracy:',accuracy_score(Y_test,np.round(predictions)), ' Precision: ',precision_score(Y_test,np.round(predictions)), ' Recall: ',recall_score(Y_test,np.round(predictions)), ' F1-Score: ',f1_score(Y_test,np.round(predictions)))
    fold_no += 1

Fold 1 Accuracy: 0.898317829889155  Precision:  0.5454545454545454  Recall:  0.06180536730821361  F1-Score:  0.1110299488677867
Fold 2 Accuracy: 0.8995154013256837  Precision:  0.5990220048899756  Recall:  0.06641366223908918  F1-Score:  0.11957052220595411
Fold 3 Accuracy: 0.8977301211530427  Precision:  0.5252225519287834  Recall:  0.04798048251558688  F1-Score:  0.08792846497764531
Fold 4 Accuracy: 0.8971730956691268  Precision:  0.49635036496350365  Recall:  0.055299539170506916  F1-Score:  0.09951219512195122
Fold 5 Accuracy: 0.8862832474585712  Precision:  0.2735632183908046  Recall:  0.06451612903225806  F1-Score:  0.1044088615924545


KeyboardInterrupt: ignored

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
model1 = RandomForestClassifier(n_estimators=100)
A = df.to_numpy()
b = labels.to_numpy()
skf = StratifiedKFold(n_splits=5)
skf.get_n_splits(A, b)

for train_ix, test_ix in skf.split(A, b):
  train_X, test_X = A[train_ix], A[test_ix]
  train_y, test_y = b[train_ix], b[test_ix]
  train_0, train_1 = len(train_y[train_y==0]), len(train_y[train_y==1])
  test_0, test_1 = len(test_y[test_y==0]), len(test_y[test_y==1])
  print('>Train: 0=%d, 1=%d, Test: 0=%d, 1=%d' % (train_0, train_1, test_0, test_1))

  model1.fit(train_X, np.ravel(train_y,order='C'))
  y_pred = model1.predict(test_X)
  print(confusion_matrix(test_y,y_pred))
  print(classification_report(test_y,y_pred))
  print(accuracy_score(test_y, y_pred))

>Train: 0=257733, 1=29508, Test: 0=64434, 1=7377
[[64266   168]
 [ 6845   532]]
              precision    recall  f1-score   support

           0       0.90      1.00      0.95     64434
           1       0.76      0.07      0.13      7377

    accuracy                           0.90     71811
   macro avg       0.83      0.53      0.54     71811
weighted avg       0.89      0.90      0.86     71811

0.9023408669980922
>Train: 0=257733, 1=29508, Test: 0=64434, 1=7377
[[64314   120]
 [ 7005   372]]
              precision    recall  f1-score   support

           0       0.90      1.00      0.95     64434
           1       0.76      0.05      0.09      7377

    accuracy                           0.90     71811
   macro avg       0.83      0.52      0.52     71811
weighted avg       0.89      0.90      0.86     71811

0.9007812173622426
>Train: 0=257734, 1=29508, Test: 0=64433, 1=7377
[[62090  2343]
 [ 6416   961]]
              precision    recall  f1-score   support

           0 

In [ ]:
importances = model1.feature_importances_
std = np.std([tree.feature_importances_ for tree in model1.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

In [ ]:
indices

array([ 5,  9,  4,  2,  6,  0,  1,  3,  7,  8, 16, 10, 11, 14, 13, 12, 15])

In [ ]:
importances

array([0.0905291 , 0.08717777, 0.09105368, 0.06844289, 0.09306185,
       0.09727001, 0.09086789, 0.06758482, 0.06578916, 0.09669344,
       0.03687046, 0.0205167 , 0.01020383, 0.01064852, 0.0149296 ,
       0.00902621, 0.04933409])