<a href="https://colab.research.google.com/github/pinakiweb/fake-review-detection/blob/main/XGB%26DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
# from nltk import bigrams,trigrams
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.decomposition import TruncatedSVD
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import re
from textblob import TextBlob

from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.stem import PorterStemmer
from collections import defaultdict
from numpy import mean
from numpy import std
from pandas import read_csv
from matplotlib import pyplot
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_validate
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.decomposition import PCA
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score, confusion_matrix
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/SWM/featuresAll.csv')
labels = pd.read_csv('/content/drive/MyDrive/SWM/labels.csv')
labels

label
0           1
1           1
2           1
3           1
4           1
...       ...
359047      0
359048      0
359049      0
359050      0
359051      0

[359052 rows x 1 columns]

In [ ]:
X1 = df.to_numpy()
Y = labels.to_numpy()
print(Y.shape)
#model = RandomForestClassifier(n_estimators=100)
model = XGBClassifier()

pca = PCA(n_components=7)
skf = StratifiedKFold(n_splits=10)
fold_no = 1
for train_index, test_index in skf.split(X1, Y):
    X1_train = X1[train_index,:]
    X1_test = X1[test_index,:]
    Y_train = Y[train_index,:]
    Y_test = Y[test_index,:]
    pca.fit(X1_train)
    X_train = pca.transform(X1_train)
    X_test = pca.transform(X1_test)  
    model.fit(X_train, np.ravel(Y_train,order='C'))
    predictions = model.predict(X_test)
    print('Fold',str(fold_no),'Accuracy:',accuracy_score(Y_test,np.round(predictions)), ' Precision: ',precision_score(Y_test,np.round(predictions)), ' Recall: ',recall_score(Y_test,np.round(predictions)), ' F1-Score: ',f1_score(Y_test,np.round(predictions)))
    fold_no += 1

(359052, 1)
Fold 1 Accuracy: 0.8974544644349134  Precision:  0.6296296296296297  Recall:  0.004608294930875576  F1-Score:  0.00914962325080732
Fold 2 Accuracy: 0.897231660446722  Precision:  0.4444444444444444  Recall:  0.0010843046896177825  F1-Score:  0.0021633315305570576
Fold 3 Accuracy: 0.8973959058626932  Precision:  0.6923076923076923  Recall:  0.002439685551640011  F1-Score:  0.004862236628849272
Fold 4 Accuracy: 0.8976465673304553  Precision:  0.85  Recall:  0.004608294930875576  F1-Score:  0.009166891345376113
Fold 5 Accuracy: 0.8961147472496866  Precision:  0.25301204819277107  Recall:  0.0056925996204933585  F1-Score:  0.011134676564156946
Fold 6 Accuracy: 0.8979807826208049  Precision:  0.7272727272727273  Recall:  0.010845986984815618  F1-Score:  0.02137323002938819
Fold 7 Accuracy: 0.8960033421529034  Precision:  0.21951219512195122  Recall:  0.004880694143167028  F1-Score:  0.009549071618037136
Fold 8 Accuracy: 0.8976465673304553  Precision:  0.8823529411764706  Recall:

In [ ]:
X1 = df.to_numpy()
Y = labels.to_numpy()
print(Y.shape)
#model = RandomForestClassifier(n_estimators=100)
#model = BaggingClassifier(n_estimators=100)
model = DecisionTreeClassifier()

pca = PCA(n_components=7)
skf = StratifiedKFold(n_splits=10)
fold_no = 1
acc0 = 0
f10 = 0
precision0 = 0
recall0 = 0
acc1 = 0
f11 = 0
precision1 = 0
recall1 = 0
for train_index, test_index in skf.split(X1, Y):
    X1_train = X1[train_index,:]
    X1_test = X1[test_index,:]
    Y_train = Y[train_index,:]
    Y_test = Y[test_index,:]
    pca.fit(X1_train)
    X_train = pca.transform(X1_train)
    X_test = pca.transform(X1_test)  
    model.fit(X_train, np.ravel(Y_train,order='C'))
    predictions = model.predict(X_test)
    cm = confusion_matrix(Y_test, np.round(predictions))
    print(cm)
    z = classification_report(Y_test,np.round(predictions))
    print(z)
    acc0 = acc0 + accuracy_score(Y_test,np.round(predictions))
    # f10 = f10 + z[0]['f1-score']
    # precision0 = precision0 + z[0]['precision']
    # recall0 = recall0 + z[0]['recall']
    # acc1 = acc1 + z[1]['accuracy']
    # f11 = f11 + z[1]['f1-score']
    # precision1 = precision1 + z[1]['precision']
    # recall1 = recall1 + z[1]['recall']

    print('Fold',str(fold_no),'Accuracy:',accuracy_score(Y_test,np.round(predictions)), ' Precision: ',precision_score(Y_test,np.round(predictions)), ' Recall: ',recall_score(Y_test,np.round(predictions)), ' F1-Score: ',f1_score(Y_test,np.round(predictions)))
    fold_no += 1
print("Accuracy 0")
print(acc0/10)
print("Precision 0")
print(precision0/10)
print("Recall 0")
print(recall0/10)
print("F1 0")
print(f10/10)
print("Accuracy 1")
print(acc1/10)
print("Precision 1")
print(precision1/10)
print("Recall 1")
print(recall1/10)
print("F1 1")
print(f11/10)

(359052, 1)
[[29382  2835]
 [ 2769   920]]
              precision    recall  f1-score   support

           0       0.91      0.91      0.91     32217
           1       0.25      0.25      0.25      3689

    accuracy                           0.84     35906
   macro avg       0.58      0.58      0.58     35906
weighted avg       0.85      0.84      0.84     35906

Fold 1 Accuracy: 0.8439258062719323  Precision:  0.24500665778961384  Recall:  0.24939007861209  F1-Score:  0.24717893605588395
[[29269  2948]
 [ 2694   995]]
              precision    recall  f1-score   support

           0       0.92      0.91      0.91     32217
           1       0.25      0.27      0.26      3689

    accuracy                           0.84     35906
   macro avg       0.58      0.59      0.59     35906
weighted avg       0.85      0.84      0.85     35906

Fold 2 Accuracy: 0.8428674873280232  Precision:  0.25234592949530815  Recall:  0.2697207915424234  F1-Score:  0.2607442348008385
[[29394  2822]
